### ISSUE TITLE
Feature request: disabling crazy-lazy for specific images

### ISSUE THREAD

**Issue by Giede** [pluginkollektiv/crazy-lazy#11]
It would be great to disable crazy-lazy effect for specific images with an extra CSS class.

Maybe with an extra css class like this example: 

```
<img src="http://www.domain.tld/images/2.jpg" class="skip_crazylazy"/>
```

Within my theme files I can add this class to e.g. the logo and crazy-lazy is not loading my logo with the lazy load effect.

Thank you! ;-)

**Comment by glueckpress** [comment]
I second the idea, this seems useful. Possibly pick a more standardized class name like `crazy-lazy-skip-image` or so.

**Comment by NormanHoehne** [comment]
Yep. Now that i need this function it seems absolutelty useful to me, too.

**Comment by NormanHoehne** [comment]
I'm not a PHP Coder,

but maybe someone of you guys can modify the following lines in plugins/crazy-lazy/inc/crazy_lazy.class.php to let the plugin first check, if the image has an class with "crazy-lazy-skip-image" as @glueckpress mentioned (Or I would suggest "no_crazy_lazy") before applying the lazy load functionalities to the image.

`    public static function prepare_images($content) {
        /* No lazy images? */
        if ( strpos($content, '-image') === false ) {
            return $content;
        }

        /* Empty gif */
        $null = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==';

        /* Replace images */
        return preg_replace(
            array(
                '#(<img class=["\'](.*?(?:wp-image-|wp-post-image).+?)["\'](.+?)src=["\'](.+?)["\'](.*?)(/?)>)#',
                '#(<img src=["\'](.+?)["\'](.+?)class=["\'](.*?(?:wp-image-|wp-post-image).+?)["\'](.*?)(/?)>)#'
            ),
            array(
                '<img class="crazy_lazy ${2}" src="' .$null. '" ${3} data-src="${4}" ${5} style="display:none" ${6}><noscript>${1}</noscript>',
                '<img src="' .$null. '" data-src="${2}" ${3} class="crazy_lazy ${4}" ${5} style="display:none" ${6}><noscript>${1}</noscript>'
            ),
            $content
        );
    }`

**Comment by swissspidy** [comment]
@NormanHoehne I self-assigned this issue recently and will look at it as soon as possible.

**Comment by NormanHoehne** [comment]
Great! 

I missed that. Thanks @swissspidy.
