### ISSUE TITLE
Broken translation on wordpress.org

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/crazy-lazy#18]
This plugin is not properly prepared for localization. If you would like to translate this plugin, please contact the author.
See: https://translate.wordpress.org/projects/wp-plugins/crazy-lazy

Maybe the missing `Text Domain: crazy-lazy` line in the plugin header?

**Comment by 2ndkauboy** [comment]
Closed in [v1.0.4](https://github.com/pluginkollektiv/crazy-lazy/releases/tag/v1.0.4)
