### ISSUE TITLE
Not properly prepared for localization

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/crazy-lazy#24]
We are not using this call `load_plugin_textdomain`

GlotPress/Translate.wordpress.org is showing this error message:

> This plugin is not properly prepared for localization (View detailed logs on Slack). If you would like to translate this plugin, please contact the author.

In Slack I can see this as the reason:
> This plugin doesn't use `load_plugin_textdomain()`.

We do not have to set this, but **if** we omit this, we have to raise the required WP version to 4.6 as mentioned in the handbook:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

@2ndkauboy Can you have a look at this? :)

**Comment by 2ndkauboy** [comment]
I would see this issue as a `won't fix`. The plugin does not have any translatable string (yet). We could probably increase the min versoin to 4.6, but that would not reflect the true minimal version anyone must have.

I know the warning in GlotPress might be annoying, but I don't really see an issue here. Unless you would say we should still increase the version number.

**Comment by Zodiac1978** [comment]
I would still recommend adding the load_plugin_textdomain-call to support the translation of the plugin description. We don't need to specify any files (there are no files) - just the call. So we don't have to raise the requirement, but we support translation(s), even if it is just the description (and the link to the plugin and so on).

**Comment by 2ndkauboy** [comment]
So you would call `load_plugin_textdomain()` just with the textdomain as the first parameter and no second and third parameter? I would be fine with doing that :)

**Comment by Zodiac1978** [comment]
Yes, exactly. :)
Dominik Schilling is doing this in Public Post Preview too.
