### ISSUE TITLE
Support for browser-level native lazy-loading

### ISSUE THREAD

**Issue by NormanHoehne** [pluginkollektiv/crazy-lazy#34]
Dear pluginkollektiv,

please consider supporting browser-level native lazy-loading. It is significantly easier for website owners to improve their website performance and it is also good for SEO since the display of images wouldn't rely on active and error-free JavaScript anymore.

Google Chrome already shipped this feature with version 76:
- https://web.dev/native-lazy-loading/

And Mozilla already put it on their development backlog:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1542784

**Comment by chesio** [comment]
Note: there's a [ticket](https://core.trac.wordpress.org/ticket/44427) aiming at implementing this feature in WordPress core.

**Comment by Zodiac1978** [comment]
See also: https://github.com/pluginkollektiv/crazy-lazy/issues/33

**Comment by patrickrobrecht** [comment]
This feature is implemented in Core already, released with [WordPress 5.5](https://wordpress.org/support/wordpress-version/version-5-5/#speed).
