### ISSUE TITLE
Add skip-lazy and data-skip-lazy for exclusion?

### ISSUE THREAD

**Issue by florianbrinkmann** [pluginkollektiv/crazy-lazy#36]
There is a initiative started by Frank, the developer of Autoptimize, to use the same class and/or attribute for exclusion from lazy loading over as many performance and lazy loading plugins as possible. Consensus was to use the class `skip-lazy` and the attribute `data-skip-lazy`.

Would that be something for Crazy Lazy to adopt?

**Comment by 2ndkauboy** [comment]
Sure, we could introduce that as a second option. The old class should still work for anyone currently using it.
