### ISSUE TITLE
Images not shown

### ISSUE THREAD

**Issue by philliproth** [pluginkollektiv/crazy-lazy#9]
It´s me again. Different pictures in Posts not showing now when I activate the plugin. Example: http://hansert-innenarchitektur.de/2015/08/10/tunnel-2/ 

The picture:

<a href="http://hansert-innenarchitektur.de/wp-content/uploads/2015/08/GDA16_HO_NOMINEE_1C-Kopie1.png"><img class="alignleft size-full wp-image-708" src="http://hansert-innenarchitektur.de/wp-content/uploads/2015/08/GDA16_HO_NOMINEE_1C-Kopie1.png" alt="GDA16_HO_NOMINEE_1C Kopie" width="236" height="131" /></a>

doesn`t show when I activate the plugin.

Also all pictures on this page: http://hansert-innenarchitektur.de/portfolio/

Can't keep the Plugin activated - sorry!

Frontpage is fine!

**Comment by swissspidy** [comment]
>Different pictures in Posts not showing now when I activate the plugin.

Can you elaborate? Is there some kind of error? Anything in the source code?

Please also try the latest version from the master branch here on GitHub. We made some tweaks today to the image detection regex.

**Comment by philliproth** [comment]
<img class="alignleft size-full wp-image-708" width="236" height="131" alt="GDA16_HO_NOMINEE_1C Kopie" src="http://hansert-innenarchitektur.de/wp-content/uploads/2015/08/GDA16_HO_NOMINEE_1C-Kopie1.png">

This is what it spits out when activated for the above:

<img  width="1000" height="666"  src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="http://hansert-innenarchitektur.de/wp-content/uploads/2015/05/023_jk141114-e1439902404842.jpg"   class="crazy_lazy attachment-post-thumbnail wp-post-image" alt=" stemcor - hansert architektur"  style="display:none" /><noscript><img width="1000" height="666" src="http://hansert-innenarchitektur.de/wp-content/uploads/2015/05/023_jk141114-e1439902404842.jpg" class="attachment-post-thumbnail wp-post-image" alt="stemcor - hansert architektur" /></noscript>

**Comment by 2ndkauboy** [comment]
For debugging it would be nice if you could give us the HTML w/ and w/o the plugin activated so we can debug the regex. It would also help to know how the images are induced into the page. Is it a static IMG tag or is it being included through a function such as `the_post_thumbnail` or similar ones.

**Comment by philliproth** [comment]
coming! ;-)

**Comment by philliproth** [comment]
Here is the code: 
https://www.philliproth.de/crazy.txt

**Comment by philliproth** [comment]
Latest Version of course!

**Comment by philliproth** [comment]
Reproducable here: http://www.wp-stripped.com/categoryname/blogpost-0/

**Comment by 2ndkauboy** [comment]
It looks like the matching RegEx catches the attributes but the replacement is doubled. Maybe the replacement happens twice. That might be tricky.

**Comment by philliproth** [comment]
Using something different for now - so no worries ;-)

**Comment by Zodiac1978** [comment]
Cross-Reference: https://wordpress.org/support/topic/works-on-page-but-not-on-front-page-loop#post-8214497
